language: php

php:
    - 7.1
    - 7.2

install:
    - composer install
    - sudo apt-get -y install python3-pip
    - sudo pip3 install -U setuptools
    - sudo pip3 install -U virtualenvwrapper
    - sudo pip3 install cherrypy
    - composer global require --update-no-dev edgedesign/phpqa phpstan/phpstan jakub-onderka/php-parallel-lint

before_script:
    - export PATH="$PATH:/home/travis/.config/composer/vendor/bin"
    - make services -j2 > /dev/null 2>&1 &
    - make start > /dev/null 2>&1 &

script:
    - composer validate --strict --no-check-lock
    - make cs-ci
    - make test
    - make mutation_test
    - make check_security
    - make qa
    - make guiding_test

after_script:
    - kill $(jobs -p)

after_success:
    - travis_retry php bin/php-coveralls -v
