make_reservation:
    path: /reserve
    controller: 'TrainReservation\Infrastructure\Http\Controllers\ReserveSeatsController'
    methods: [POST]

status:
    path: /
    controller: 'TrainReservation\Infrastructure\Http\Controllers\HealthCheck'
