make_reservation:
    path: /reserve
    controller: 'TrainReservation\Infrastructure\Http\PrimaryAdapters\MakeReservation'
    methods: [POST]

status:
    path: /
    controller: 'TrainReservation\Infrastructure\Http\PrimaryAdapters\HealthCheck'
