index:
    path: /
    controller: 'TrainReservation\Controller\Home::index'
    methods: [GET]

reserve_seats:
    path: /reserve
    controller: 'TrainReservation\Infrastructure\Adapters\Http\TicketOfficeAdapter::reserveSeats'
    methods: [POST]
