index:
    path: /
    controller: 'TrainReservation\Infrastructure\Adapters\Http\Controller\Home::ok'
    methods: [GET]

reserve_seats:
    path: /reserve
    controller: 'TrainReservation\Infrastructure\Adapters\Http\Controller\TicketOfficeAdapter::reserveSeats'
    methods: [POST]
