reserve_seats:
    path: /reserve
    controller: 'TrainReservation\Infrastructure\Http\Controller\TicketOfficeAdapter::reserveSeats'
    methods: [POST]

status:
    path: /
    controller: 'TrainReservation\Infrastructure\Http\Controller\Status::ok'
